#Note the syntax ${{}} for compile time and $[] for runtime expressions.
variables:

  # Deployment Conditions 
  isMain: ${{  eq(variables['Build.SourceBranch'], 'refs/heads/main')  }}
  isProd: ${{  eq(variables['Build.SourceBranch'], 'refs/heads/production')  }}
  # Zero Trust Principle 
  isFork:      ${{  eq(variables['System.PullRequest.IsFork'], 'True') }}
  isPR:        ${{  eq(variables['Build.Reason'], 'PullRequest')  }}
  isScheduled: ${{  eq(variables['Build.Reason'], 'Schedule')  }}
  isTrustedCI: ${{  and( eq(variables.isFork, 'False'), eq(variables.isPR, 'False'), eq(variables.isScheduled, 'False'))   }}
  deployMain:  ${{  and( eq(variables.isMain, 'True'), eq(variables.isTrustedCI, 'True') )  }}
  isTag:       ${{  startsWith(variables['Build.SourceBranch'], 'refs/tags/v')  }}

  # Docker 
  dockerImageName: luisenalvar/weatherapi
  dockerServiceConnect: DockerHubSerConnect
  ${{ if eq(variables.isTag, 'False')  }}:
    imagetag: dev_latest

  # Terraform 
  # TerraformVariables: TerraformEnvVars #unable to use this variable on terraform.yaml under group

  # dev-pipeline.yam or prod-pipeline.yaml will overwrite value 
  containerInstanceAzureName: unset
