#Note the syntax ${{}} for compile time and $[] for runtime expressions.
variables:

  # Deployment Conditions 
  isMain: ${{  eq(variables['Build.SourceBranch'], 'refs/heads/main')  }}
  isProd: ${{  eq(variables['Build.SourceBranch'], 'refs/heads/production')  }}

  # Docker 
  imageName: luisenalvar/weatherapi
  containerRegistry: DockerHubSerConnect

  # Terraform 
  tfEnvironmentVariables: TerraformEnvVars

  # dev-pipeline.yam or prod-pipeline.yaml will overwrite value 
  containerInstanceAzureName: unset
