jobs:
- job: BuildAndPush 
  displayName: Build and Push Image 
  pool: 
    vmImage: 'ubuntu-latest'
  steps:
  - task: Docker@2
    inputs:
      containerRegistry: '$(dockerServiceConnect)'
      repository: '$(imageName)'
      command: 'buildAndPush'
      Dockerfile:  '**/Dockerfile'
      tags: | 
        $(tag)